name: wine
favicon: null
layout_spectrum: 0.5063153631053865
typography_spectrum: 0.31109479861333966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5760346557945013
  lightness: 0.6295359623618424
  saturation: 0.6083569217007607
  rhythmicContrast: 0.7551772817969322
purpose: []
